export enum ElectronIpcEvent {
    MARK = "MARK",
    LOG = "LOG",
    CODE_RESULT = "CODE",
    CODE_EXEC = "CODE_EXEC",
    CODE_EXEC_RESULT = "CODE_EXEC_RESULT",
    SET_CAN_CLICK = "SET_CAN_CLICK",
    OPEN_EDITOR = "OPEN_EDITOR",
    DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION",
    KEY_PRESSED = "KEY_PRESSED",
    KEY_RELEASED = "KEY_RELEASED",
    OPEN_EXTERNAL_WINDOW = "OPEN_EXTERNAL_WINDOW",
    UPDATE_STATE = "UPDATE_STATE",
    VERSION_INFO = "VERSION_INFO",
    INITAL_STATE = "inital_state",
    COLLAPSE_APP = "COLLAPSE_APP",
    NAVIGATE = "NAVIGATE",
    FOCUS = "FOCUS"
}